version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py
  # Fail on all warnings to avoid broken references
  fail_on_warning: true

python:
  install:
    - requirements: docs/requirements.txt
