AWSTemplateFormatVersion: 2010-09-09
Description: SDLF Foundations in proserve domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rProserve:
        Type: awslabs::sdlf::foundations::MODULE
        Properties:
            pPipelineReference: !Ref pPipelineReference
            pChildAccountId: 111111111111
            pOrg: forecourt
            pDomain: proserve
            pEnvironment: dev
